### ISSUE TITLE
Nodes list filtering by tags cannot be reset by removing the tag

### ISSUE THREAD

**Issue by mihilie** [mkalus/segrada#1]
I want to start by saying that I think Sagrada is an **amazing** software, that could be helpful in many ways!

I'd like to report an issue I found in the "List Nodes" window...

Steps to repro:
- in the "Tags" field, enter a tag
- click "Filter"
- remove the tag entered in the "Tags" field
- click "Filter": instead of resetting the filtering, the tag reappears, so the filtering stays in the previous state.

There is of course the "Reset" link that is doing the job, but I think that emptying the "Tags" 
field should have the same effect.

Thank you!
Mihai

**Comment by mkalus** [comment]
Fixed in df15c8cd58efbcb3f55855e8920ba7dc690eaccd
