### ISSUE TITLE
Segrada seems to corrupt its Node database if you delete a Pictogram associated to a Node

### ISSUE THREAD

**Issue by ramiromagalhaes** [mkalus/segrada#46]
It seems I corrupted my database. What I did was:

1. Create a Node
1. Create a Pictogram
1. Edit the Node and associate it with the Pictogram
1. Delete the Pictogram
1. List all your Nodes
1. Boom

After doing this I tried to [load the database in an OrientDB instance](https://github.com/mkalus/segrada/blob/master/src/main/resources/documentation/en/orientdb.md) to fix whatever happened and I got a "Index type SPATIAL is not supported by the engine 'LUCENE'."

You should note that all other lists (sources, files, pictograms, etc.) keep working fine.

I did not find a way to read Segrada logs, so I cannot post them here yet.

Help?

**Comment by mkalus** [comment]
Thanks for the info. I will look into this asap.

**Comment by mkalus** [comment]
Fixed and rolled out in the next version.
