### ISSUE TITLE
Cant login using admin/admin on OriendDb

### ISSUE THREAD

**Issue by tetracilin** [mkalus/segrada#48]
OrientDb gives a 401 unauthorized ; invalid username & password error.

**Comment by mkalus** [comment]
Could you relate what you are trying to accomplish? I take it that you use a standalone version of OrientDb running as a server. Have you created a database that Segrada can use as its database?

**Comment by mkalus** [comment]
Might be a version problem/bug. What DB version are you using?

**Comment by mkalus** [comment]
My guess: If you run OrientDb server, you have to add the lucene index to the lib folder as it is not bundled in the server package: http://orientdb.com/docs/2.2/Spatial-Index.html
