### ISSUE TITLE
Graph is not updated

### ISSUE THREAD

**Issue by maxhq** [mkalus/segrada#51]
Hi, I am using the Segrada version from 2019-04-09. Great tool!
It seems that the graph does not reflect updated links between nodes: I can add links or change their color, the graph stays the same. The graph refresh button does not seem to work. Or am I missing something?

**Comment by mkalus** [comment]
No, you are not missing something. The nodes are simply not upgraded once they are on the graph - so this is a bug indeed!

**Comment by mkalus** [comment]
Fixed and scheduled for next release.
