### ISSUE TITLE
Support for non latin characters

### ISSUE THREAD

**Issue by dubmassacre** [mkalus/segrada#55]
It would be nice if segrada could support data entry in non-latin characters for entities.

Whenever user types a non-latin character string, save fails and receives a message:

```
ERROR org.segrada.service.repository.orientdb.base.AbstractOrientDbRepository  - Exception thrown while saving entity.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
```

System configuration:
MacOS 10.14.6
Segrada 0.2.8

**Comment by mkalus** [comment]
@dubmassacre : I cannot reproduce this behaviour any more in the current version? Do you still have this problem?

**Comment by dubmassacre** [comment]
I cannot execute successfully the lastest version. 0.5.4 I get a 'java.lang.IllegalStateException: Unable to load cache' 

```
INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @654b5005
java.lang.IllegalStateException: Unable to load cache item

```

**Comment by mkalus** [comment]
Thanks for the hint. There was a bug in the old sluggify solution. I added a solution which will fix this issue. The update is scheduled for the next release (v0.5.5).

**Comment by dubmassacre** [comment]
Tested v0.5.5. No any issues.
