### ISSUE TITLE
[Feature Request] [Wishlist] - Multiple Synonyms on TAGS

### ISSUE THREAD

**Issue by StoltHD** [mkalus/segrada#57]
It would be great if it could be possible to get synonyms on TAGS...

It could be i.e. to be able to add tag names in different languages, or when multiple words can mean the same thing...
It would be of great benefits when using tag hierarchy, not having multiple sub hierarchies (i.e. for languages) with the same meaning...

**Comment by mkalus** [comment]
Ok, implemented and scheduled for next release.
