### ISSUE TITLE
Is this project deead?

### ISSUE THREAD

**Issue by StoltHD** [mkalus/segrada#59]
Just wondering if the project are dead/depricated?

**Comment by mkalus** [comment]
It's not dead - I just don't have time to proceed further right now. I am also looking for help in programming etc.

**Comment by StoltHD** [comment]
Sad tto hear that you can't get any help with the programming... If I did know how to I should have helped, because this is a good tool and it could be really great with a few more features...

Hope you find time and some developer thats interested in this kind of software...
