### ISSUE TITLE
Fault: Color on edges change if moving Nodes in the graph

### ISSUE THREAD

**Issue by StoltHD** [mkalus/segrada#72]
If I move a Node in the graph view that has a edge/link that has a custom color, i.e. green or blue, the color of the edge change to grey.

If I reload the graph view the correct color occur again, but the Nodes has moved back to a default position in the graph, and as soon as I try to move one of the Nodes again, the edge change color again back to "default" grey.

EDIT: The color of the Edge do switch back to the custom color AFTER you click out of the Node so that the node is no longer selected, but it is a delay on this, it would have been better if the edge color kept the custom color when moving connected Nodes.

**Comment by mkalus** [comment]
Ok, this seems to be a vis.js related bug. I am trying to update vis.js in order to get rid of this bug (recent versions of visjs work fine regarding colors).

**Comment by mkalus** [comment]
Ok, updated vis.js to newest version and the bug is gone. Took some CSS and code changes in order to work 😄

Scheduled for the next release (0.5.1)

**Comment by StoltHD** [comment]
I still have this problem for some of my Nodes/Edges in the graph after update to 0.5.1, but not for every node.

To be sure that I didn't have anything old "hanging", I did delete the old install folder and then copied the new version to that SSD.

The problem now is when I select a node, the edges for that selected node goes grey.
I think this has something to do with the default color for selected Nodes and Edges.

It would be great if that either was customizable, or maybe only show a glow on the edges for the selected nodes, because when you have many nodes and edges in the graph, the grey edges is not very visible.

A glow in the same color but brighter, that is set for the edge might be a better way to show a selected nodes edges.

**Comment by mkalus** [comment]
It works on my machine. Have you tried to delete your browser's cache?

**Comment by StoltHD** [comment]
Yes, and I have tried with a browser that I newer have used with Segrada or connected to localhost.
This occur both in MS Edge and Firefox.

It only occur on selected nodes, so you need to click the node to select it.

If a edge connected to that node has a custom set color, it's color change to grey.

**Comment by mkalus** [comment]
Ok, there is a highlight color option in vis.js (=> see [example](https://visjs.github.io/vis-network/examples/network/edgeStyles/colors.html) and [code](https://github.com/visjs/vis-network/blob/master/examples/network/edgeStyles/colors.html)).

Fixing it now!
