### ISSUE TITLE
unable to include sources

### ISSUE THREAD

**Issue by LegoDerGute** [mkalus/segrada#8]
When I fill the fields "Source" and "Reference text" the following error message appears: "source must not be empty" and the fields are empty again...

![segrada-source error scr](https://cloud.githubusercontent.com/assets/16256284/11839812/08a6f890-a3f1-11e5-93b1-4b2dab2f740b.png)

**Comment by mkalus** [comment]
You have to select the sources found either by clicking on them or navigation with the keys and pressing enter.

**Comment by mkalus** [comment]
Add small help text to input fields requiring selection.

**Comment by mkalus** [comment]
Fixed with 4350817937fc43263d140c0dd97534a931a712ce.
